apiVersion: apps/v1
kind: Deployment
metadata:
  name: jokeservice
  labels:
    app: jokeservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jokeservice
  template:
    metadata:
      labels:
        app: jokeservice
    spec:
      containers:
      - name: fastapi
        image: localhost/jokeservice
        env:
        - name: AZURE_OPENAI_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: openai
              key: AZURE_OPENAI_ENDPOINT
        - name: AZURE_OPENAI_KEY
          valueFrom:
            secretKeyRef:
              name: openai
              key: AZURE_OPENAI_KEY
        - name: OPENAI_API_VERSION
          valueFrom:
            secretKeyRef:
              name: openai
              key: OPENAI_API_VERSION
        - name: OPENAI_API_TYPE
          valueFrom:
            secretKeyRef:
              name: openai
              key: OPENAI_API_TYPE
        ports:
        - containerPort: 8001
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: jokeservice
  labels:
    app: jokeservice
spec:
  ports:
  - port: 8001
    protocol: TCP
    targetPort: 8001
    name: http
  selector:
    app: jokeservice

---
